version: '3'
services:
  myblog:
    image: jiangzwyz/myrepo:myblog
    ports:
      - "4000:4000"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - ~/myWorkspace/myproject/myblog/source:/app/source